name: testing dispatcher

on:
  push:
    branches: ['dev']
  workflow_dispatch:
    inputs:
      run_stage_1:
        description: 'Run Stage 1 (Build)'
        required: true
        type: boolean
        default: false  # Will be checked by default
      run_stage_2:
        description: 'Run Stage 2 (Deploy)'
        required: true
        type: boolean
        default: false # Will be unchecked by default
      run_stage_3:
        description: 'Run Stage 3 (Destroy)'
        required: true
        type: boolean
        default: false # Will be unchecked by default

jobs:
  # --- STAGE 1 ---
  stage_1_build:
    name: Stage 1 Job
    # This job ONLY runs if the 'run_stage_1' checkbox is checked
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_stage_1) }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute Build
        run: echo "Executing Stage 1..."

  # --- STAGE 2 ---
  stage_2_deploy:
    name: Stage 2 Job
    # This job ONLY runs if the 'run_stage_2' checkbox is checked
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_stage_2) }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy
        run: echo "Executing Stage 2..."

  stage_3_destroy:
    name: Stage 3 Job
    # This job ONLY runs if the 'run_stage_2' checkbox is checked
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_stage_3) }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute destroy
        run: echo "Executing Stage 3..."
